spring.application.name=scheduler

# PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.datasource.url=xxx
spring.datasource.username=xxx
spring.datasource.password=xx
spring.datasource.hikari.schema=public

# Liquibase migrations
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml